trigger: none
pool:
    vmImage: 'ubuntu-latest'
variables:
- group: GitHub

stages:
- stage: 'Build'
  jobs:
  - template: ../templates/gradle.yml
    parameters:
      workingDirectory: 'project1'
      gitCiToken: "$(GH_TOKEN)"
      gitCiUserMail: "$(GH_USER_MAIL)"
      gitCiUserName: "$(GH_USER_NAME)"
- template: ../templates/store_blob.yml
  parameters:
    azSubRmConnection: "$(AZ_RM_CONNECTION)"