trigger: none
pool:
    vmImage: 'ubuntu-latest'

stages:
- stage: 'Build'
  jobs:
  - template: ../templates/gradle.yml
    parameters:
      workingDirectory: 'project1'
- template: ../templates/store_blob.yml