trigger: none
pool:
    vmImage: 'ubuntu-latest'
variables:
    - group: DEFAULT_PROJECT_SETTINGS

stages:
- stage: Add_and_configure_AZ_DevOps_extension
  jobs:
  - job: Add_and_configure_AZ_DevOps_extension
    steps:
        # Updating the python version available on the linux agent
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          architecture: 'x64'
      # Updating pip to latest
      - script: python -m pip install --upgrade pip
        displayName: 'Upgrade pip'
        # Updating to latest Azure CLI version.
      - script: pip install --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge
        displayName: 'upgrade azure cli'
      - script: az --version
        displayName: 'Show Azure CLI version'
      - script: az extension add -n azure-devops
        displayName: 'Install Azure DevOps Extension'
      - script: echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
        env:
          AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
        displayName: 'Login Azure DevOps Extension'
      - script: az devops configure --defaults organization=$(AZ_ORGANIZATION) project=$(AZ_PROJECT) --use-git-aliases true
        displayName: 'Set default Azure DevOps organization and project'
      - script: |
            set +e ; for fn in $(find . -mindepth 2 -name "azure-pipelines.yml"); do
            pipeline_ini_base=${fn%.*}
            INI_CONTENT=$(sed "s/;/#/g;s/\\s*=\\s*/=/g;/\\[/d" ${pipeline_ini_base}.ini)
            eval "$INI_CONTENT"
            az pipelines list | grep -E "\\"name\\":\\s\\"${pipeline_name}\\","
            if [ $? -ne 0 ]; then
                az pipelines create --name $pipeline_name --description "$pl_description" --service-connection $(AZ_REPO_ENDPOINT_ID) \
                --repository $(Build.Repository.Uri) --branch $(Build.SourceBranchName) --yml-path $fn
            else
                pid=$(az pipelines list --name $pipeline_name --query  "[].id[]" | grep -E -v "\\[|\\]")
                az pipelines update --id $pid --description "$pl_description" --yml-path $fn
            fi
            done




