parameters:
- name: workingDirectory
  type: string
  default: ''

jobs:
    - job: BuildJob
      steps:
      - checkout: self
      # Allow scripts to access the system token so that the pipeline can push git changes (eg. version bump)
      persistCredentials: true
      # Checkout branch since by default Azure Pipelines do checkouts of specific commits (detached HEAD)
      # and we need to be at master to be able to push version bump changes.
      # We need to use a powershell script here to extract the proper branch name by removing 'refs/heads/' from the BUILD_SOURCEBRANCH variable
      # (eg. 'refs/heads/feature/feat-a' becomes 'feature/feat-a').
      - powershell: write-host "##vso[task.setvariable variable=branch]$($env:BUILD_SOURCEBRANCH.substring($env:BUILD_SOURCEBRANCH.indexOf('/', 5) + 1))"
        displayName: "Extract the branch name"
      - script: |
        sudo apt-get update
        sudo apt-get -y install tree
        git checkout $(branch)
        git status
        ls -l /home/vsts/work/1/s
        tree /home/vsts/work/1/s
        displayName: "Checkout branch"
      - task: Gradle@2
        inputs:
          workingDirectory: ${{ parameters.workingDirectory }}
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'release'
      - task: PublishPipelineArtifact@1
        inputs:
          path: $(System.DefaultWorkingDirectory)/build
          artifact: gradleBuild