parameters:
- name: workingDirectory
  type: string
  default: ''
jobs:
    - job: BuildJob
      steps:
      - task: Gradle@2
        inputs:
          workingDirectory: ${{ workingDirectory }}
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'release'
      - task: PublishPipelineArtifact@1
        inputs:
          path: $(System.DefaultWorkingDirectory)/build
          artifact: gradleBuild